### ISSUE TITLE
Set up infrastructure for local "kb-in-a-box" development.

### ISSUE THREAD

**Issue by LOZORD** [STAR-TIDES/kb#4]
This should include:

- Building everything (backend+frontend) into a docker image.
- Starting the web server on localhost.
- Starting a local MongoDB client.
- Optional: populate the DB with some fake data for testing.

**Comment by ekivolowitz** [comment]
@LOZORD This should be resolved when we merge in [PR-1](https://github.com/STAR-TIDES/kb/pull/1) right?
